# Файл docker-compose должен начинаться с тега версии.
# Используем "3.8" так как это - самая свежая версия на момент написания этого кода.
# Подробнее о различиях в версиях конфигурации docker-compose можно посмотреть на официальном ресурсе https://docs.docker.com/compose/compose-file/compose-versioning/#compatibility-matrix
version: "3.8"

# Следует учитывать, что docker-compose работает с сервисами.
# 1 сервис = 1 контейнер.
# Сервисом может быть клиент, сервер, сервер баз данных...
# Раздел, в котором будут описаны сервисы, начинается с 'services'.

services:

  # Первый сервис (контейнер): сервер.
  server:
    # Ключевое слово "build" позволяет задать путь к файлу Dockerfile, который нужно использовать для создания образа,
    # который позволит запустить сервис.
    # Здесь 'server/' соответствует пути к папке сервера, которая содержит соответствующий Dockerfile.
    build: server/

    # Команда, которую нужно запустить после создания образа.
    # Следующая команда означает запуск "python ./server.py".
    command: python ./server.py

    # Порты для перенаправления.
    # [порт компьютера]:[порт контейнера]
    ports:
      - "1234:1234"

  # Второй сервис (контейнер): клиент.
  client:
    # Путь к Dockerfile для клиентской части системы.
    build: client/

    # Команда, которую нужно запустить после создания образа.
    # Следующая команда означает запуск "python ./client.py".
    command: python ./client.py

    # Настройка сети.
    network_mode: host

    # Зависимости сервиса 'client' от сервиса 'server'.
    depends_on:
      - server
